In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('processed_clean_data.csv')
df

name  rating  \
0                      C K     3.0   
1            Josie Lyngdoh     4.0   
2            sandeep rawat     5.0   
3           Ashutosh Kumar     4.0   
4         P.VEERA NARENDRA     5.0   
5            Anita Kochhar     4.0   
6                 G.l.babu     5.0   
7            Deokant singh     4.0   
8            Savita sharma     4.0   
9                  SivaRam     3.0   
10          Prashant Kumar     3.0   
11                   Mohan     4.0   
12             Placeholder     5.0   
13         sudeshna sarkar     4.0   
14                  Kavita     5.0   
15             Manish raut     5.0   
16        Kanpuriya Bhaiya     5.0   
17            Sujith kumar     5.0   
18                    Syed     5.0   
19            Tanveer Khan     2.0   
20                   Akash     5.0   
21            Sujeet kumar     5.0   
22              ravi singh     5.0   
23             Srinath A.V     5.0   
24                 amritha     5.0   
25            Arun Vijay.V     5.0   
26         Terry Fernandes     5.0   
27             Truth Devil     5.0   
28                 Aman K.     5.0   
29           Kajari Sarkar     5.0   
30         Shivratan Gupta     1.0   
31             Saloni Jain     4.0   
32          Yash Chourasia     5.0   
33                   Mouli     5.0   
34  Vasundhara Tahilramani     5.0   
35            Karan khanna     5.0   
36               Pramod K.     4.0   
37                 Santosh     5.0   
38      shobhit chaturvedi     5.0   
39            Gagan rohila     5.0   
40        mohammed maqbool     5.0   
41          anushka sharma     5.0   
42          Abhijeet Pawar     5.0   

                                                title  \
0                                   Publicity tactic.   
1                                   Its exactly shown   
2                                                Nice   
3                                               Good.   
4                                              Superb   
5                                      Gentle on gums   
6                                                Good   
7                                                Good   
8                                   Normal toothpaste   
9                                                  OK   
10  Not recommended for normal usage...Only for th...   
11    It's Good for Gum problems.. Very nice product.   
12                            It's a genuine products   
13                                               Good   
14                               A burst of freshness   
15                                               Good   
16                              Good haldi toothpaste   
17                              Excellent toothpaste.   
18                                   Different flavor   
19                               Bad buy, do not buy.   
20                                       Nice nd best   
21                            Awesome test toothpaste   
22                                  Very good product   
23                                    Good toothpaste   
24                             Really good Toothpaste   
25                                Working wonders...!   
26                                          Very good   
27                               Excellent Toothpaste   
28       Very useful and very nice product for mouth.   
29  Excellent product. Hello friends just go for i...   
30                     Not having any special quality   
31                               Good value for money   
32                               Flavoured toothpaste   
33                                             Review   
34                                excellent product!!   
35                                             STRONG   
36                  Better than earlier colgate paste   
37                              Gum expert toothpaste   
38                                               Good   
39                                       Nice product   
40          

In [3]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification

from scipy.special import softmax

In [4]:
roberta ='cardiffnlp/twitter-roberta-base-sentiment'

In [5]:
model = AutoModelForSequenceClassification.from_pretrained(roberta)

In [6]:
tokenizer = AutoTokenizer.from_pretrained(roberta)

In [7]:
labels=['Negative','Neutral','Positive']


In [8]:
title_review=df['title_reveiws'].tolist()

In [9]:

#Sentiment  Analysis

encode_review = tokenizer(title_review,return_tensors='pt',padding=True)

In [10]:
encode_review

{'input_ids': tensor([[    0, 22649,  1571,  ...,     1,     1,     1],
        [    0, 30872,  2230,  ...,     1,     1,     1],
        [    0, 41541, 16911,  ...,     1,     1,     1],
        ...,
        [    0, 16713,   428,  ...,     1,     1,     1],
        [    0, 13584,  8667,  ...,     1,     1,     1],
        [    0, 18551,  7357,  ...,     1,     1,     1]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [11]:
output = model(encode_review['input_ids'],encode_review['attention_mask'])
output

SequenceClassifierOutput(loss=None, logits=tensor([[ 1.4149e+00,  5.8687e-01, -1.9882e+00],
        [-2.6202e+00,  1.8302e-01,  2.7873e+00],
        [-1.6820e+00,  3.5915e-01,  1.8006e+00],
        [-2.3425e+00, -4.2384e-02,  3.0348e+00],
        [-2.2745e+00,  4.5229e-01,  2.2581e+00],
        [-8.1849e-01,  5.3031e-01,  3.4630e-01],
        [-2.1473e+00, -1.1911e-01,  2.8797e+00],
        [-2.3399e+00,  6.8152e-01,  1.7946e+00],
        [-1.1229e+00,  4.8133e-01,  8.7816e-01],
        [ 1.3273e+00,  4.8265e-01, -2.0596e+00],
        [ 2.6428e+00, -1.6835e-01, -2.5698e+00],
        [-2.3471e+00, -2.8830e-01,  3.3442e+00],
        [-2.5980e+00,  7.0689e-01,  2.1311e+00],
        [-2.6260e+00, -3.8483e-01,  3.6315e+00],
        [-2.4984e+00,  1.2209e-01,  2.8593e+00],
        [-2.3325e+00,  2.3537e-01,  2.5607e+00],
        [-2.8017e+00,  1.1974e-01,  3.2649e+00],
        [-2.7686e+00, -1.0093e-01,  3.5577e+00],
        [-2.5401e+00, -3.5363e-01,  3.6808e+00],
        [ 2.7209e+00, -2.3

In [12]:
output[0]

tensor([[ 1.4149e+00,  5.8687e-01, -1.9882e+00],
        [-2.6202e+00,  1.8302e-01,  2.7873e+00],
        [-1.6820e+00,  3.5915e-01,  1.8006e+00],
        [-2.3425e+00, -4.2384e-02,  3.0348e+00],
        [-2.2745e+00,  4.5229e-01,  2.2581e+00],
        [-8.1849e-01,  5.3031e-01,  3.4630e-01],
        [-2.1473e+00, -1.1911e-01,  2.8797e+00],
        [-2.3399e+00,  6.8152e-01,  1.7946e+00],
        [-1.1229e+00,  4.8133e-01,  8.7816e-01],
        [ 1.3273e+00,  4.8265e-01, -2.0596e+00],
        [ 2.6428e+00, -1.6835e-01, -2.5698e+00],
        [-2.3471e+00, -2.8830e-01,  3.3442e+00],
        [-2.5980e+00,  7.0689e-01,  2.1311e+00],
        [-2.6260e+00, -3.8483e-01,  3.6315e+00],
        [-2.4984e+00,  1.2209e-01,  2.8593e+00],
        [-2.3325e+00,  2.3537e-01,  2.5607e+00],
        [-2.8017e+00,  1.1974e-01,  3.2649e+00],
        [-2.7686e+00, -1.0093e-01,  3.5577e+00],
        [-2.5401e+00, -3.5363e-01,  3.6808e+00],
        [ 2.7209e+00, -2.3114e-01, -2.4787e+00],
        [-2.4971e+00

In [13]:
scores=[]
for i in range(len(output[0])):
    scores.append(output[0][i].detach().numpy())
    
scores


[array([ 1.4149027,  0.58687  , -1.9882454], dtype=float32),
 array([-2.6202264 ,  0.18302023,  2.787275  ], dtype=float32),
 array([-1.6819637 ,  0.35914987,  1.800571  ], dtype=float32),
 array([-2.342451  , -0.04238365,  3.0347621 ], dtype=float32),
 array([-2.2744594 ,  0.45229283,  2.258141  ], dtype=float32),
 array([-0.8184877 ,  0.53030705,  0.3463031 ], dtype=float32),
 array([-2.1472688 , -0.11910543,  2.8797143 ], dtype=float32),
 array([-2.3399074,  0.6815213,  1.7946267], dtype=float32),
 array([-1.1228884 ,  0.48132676,  0.87816477], dtype=float32),
 array([ 1.3273464,  0.4826537, -2.059567 ], dtype=float32),
 array([ 2.642805 , -0.1683498, -2.5698318], dtype=float32),
 array([-2.3470957 , -0.28829613,  3.3441558 ], dtype=float32),
 array([-2.5979562 ,  0.70688605,  2.1310918 ], dtype=float32),
 array([-2.6260085, -0.3848287,  3.6315465], dtype=float32),
 array([-2.4984047 ,  0.12209299,  2.8593485 ], dtype=float32),
 array([-2.3324518 ,  0.23536547,  2.5606565 ], dtype=f

In [14]:
scores[0][0]

1.4149027

In [15]:
scores[0]

array([ 1.4149027,  0.58687  , -1.9882454], dtype=float32)

In [16]:
scores_scaler=[]
for i in range(len(scores)):
    x=softmax(scores[i])
    scores_scaler.append(x)

In [17]:
scores_scaler[0][0]

0.6801905

In [18]:
dict_list={}
for j in range(len(scores_scaler)):
    for i in range(len(labels)):
        l = labels[i]
        s = scores_scaler[0][i]
        print(l,s)
        
    print('**'*25)


Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0.6801905
Neutral 0.29718062
Positive 0.022628833
**************************************************
Negative 0

In [19]:
negative=[]
neutral=[]
positive=[]
for i in range(len(scores_scaler)):
    negative.append(scores_scaler[i][0])
    neutral.append(scores_scaler[i][1])
    positive.append(scores_scaler[i][2])


In [20]:
df['negative'] = negative
df['neutral'] = neutral
df['positive'] = positive
df.head()

name  rating              title  \
0               C K     3.0  Publicity tactic.   
1     Josie Lyngdoh     4.0  Its exactly shown   
2     sandeep rawat     5.0               Nice   
3    Ashutosh Kumar     4.0              Good.   
4  P.VEERA NARENDRA     5.0             Superb   

                                     reviews  \
0  Nothing new. Only to make customers fool.   
1                       Really happy with it   
2                                       Nice   
3                      It is good for my gum   
4                                 Good taste   

                                       title_reveiws  \
0  Publicity tactic. Nothing new. Only to make cu...   
1             Its exactly shown Really happy with it   
2                                          Nice Nice   
3                        Good. It is good for my gum   
4                                  Superb Good taste   

                                        clean_text  Length_of_title_review  \
0  publicity tactic nothing new make customer fool                      59   
1                       exactly shown really happy                      38   
2                                             nice                       9   
3                                         good gum                      27   
4                                superb good taste                      17   

   Length_of_clean_text  negative   neutral  positive  
0                    47  0.680191  0.297181  0.022629  
1                    26  0.004157  0.068579  0.927264  
2                     4  0.024248  0.186686  0.789066  
3                     8  0.004398  0.043866  0.951736  
4                    17  0.009151  0.139849  0.851000

In [21]:
df.columns

Index(['name', 'rating', 'title', 'reviews', 'title_reveiws', 'clean_text',
       'Length_of_title_review', 'Length_of_clean_text', 'negative', 'neutral',
       'positive'],
      dtype='object')

In [22]:
max_cols = df[['negative','neutral','positive']].idxmax(axis=1)

In [23]:
df['Sentiment_having_max_score'] = max_cols

In [24]:
df

name  rating  \
0                      C K     3.0   
1            Josie Lyngdoh     4.0   
2            sandeep rawat     5.0   
3           Ashutosh Kumar     4.0   
4         P.VEERA NARENDRA     5.0   
5            Anita Kochhar     4.0   
6                 G.l.babu     5.0   
7            Deokant singh     4.0   
8            Savita sharma     4.0   
9                  SivaRam     3.0   
10          Prashant Kumar     3.0   
11                   Mohan     4.0   
12             Placeholder     5.0   
13         sudeshna sarkar     4.0   
14                  Kavita     5.0   
15             Manish raut     5.0   
16        Kanpuriya Bhaiya     5.0   
17            Sujith kumar     5.0   
18                    Syed     5.0   
19            Tanveer Khan     2.0   
20                   Akash     5.0   
21            Sujeet kumar     5.0   
22              ravi singh     5.0   
23             Srinath A.V     5.0   
24                 amritha     5.0   
25            Arun Vijay.V     5.0   
26         Terry Fernandes     5.0   
27             Truth Devil     5.0   
28                 Aman K.     5.0   
29           Kajari Sarkar     5.0   
30         Shivratan Gupta     1.0   
31             Saloni Jain     4.0   
32          Yash Chourasia     5.0   
33                   Mouli     5.0   
34  Vasundhara Tahilramani     5.0   
35            Karan khanna     5.0   
36               Pramod K.     4.0   
37                 Santosh     5.0   
38      shobhit chaturvedi     5.0   
39            Gagan rohila     5.0   
40        mohammed maqbool     5.0   
41          anushka sharma     5.0   
42          Abhijeet Pawar     5.0   

                                                title  \
0                                   Publicity tactic.   
1                                   Its exactly shown   
2                                                Nice   
3                                               Good.   
4                                              Superb   
5                                      Gentle on gums   
6                                                Good   
7                                                Good   
8                                   Normal toothpaste   
9                                                  OK   
10  Not recommended for normal usage...Only for th...   
11    It's Good for Gum problems.. Very nice product.   
12                            It's a genuine products   
13                                               Good   
14                               A burst of freshness   
15                                               Good   
16                              Good haldi toothpaste   
17                              Excellent toothpaste.   
18                                   Different flavor   
19                               Bad buy, do not buy.   
20                                       Nice nd best   
21                            Awesome test toothpaste   
22                                  Very good product   
23                                    Good toothpaste   
24                             Really good Toothpaste   
25                                Working wonders...!   
26                                          Very good   
27                               Excellent Toothpaste   
28       Very useful and very nice product for mouth.   
29  Excellent product. Hello friends just go for i...   
30                     Not having any special quality   
31                               Good value for money   
32                               Flavoured toothpaste   
33                                             Review   
34                                excellent product!!   
35                                             STRONG   
36                  Better than earlier colgate paste   
37                              Gum expert toothpaste   
38                                               Good   
39                                       Nice product   
40          

In [25]:
df.to_csv('SENTIMENT_ANALYSIS_USING_twitter-roberta-base-sentiment_on_raw_text.csv',index=False)

In [26]:
print(max_cols)

0     negative
1     positive
2     positive
3     positive
4     positive
5      neutral
6     positive
7     positive
8     positive
9     negative
10    negative
11    positive
12    positive
13    positive
14    positive
15    positive
16    positive
17    positive
18    positive
19    negative
20    positive
21    positive
22    positive
23    positive
24    positive
25    positive
26    positive
27    positive
28    positive
29    positive
30    negative
31    positive
32    positive
33    positive
34    positive
35    positive
36    positive
37    positive
38    positive
39    positive
40    positive
41    positive
42    positive
dtype: object


In [27]:
for i in range(len(scores_scaler)):
    scores_scaler

In [28]:
scores_scaler

[array([0.6801905 , 0.29718062, 0.02262883], dtype=float32),
 array([0.00415677, 0.06857882, 0.92726445], dtype=float32),
 array([0.02424755, 0.18668619, 0.7890662 ], dtype=float32),
 array([0.00439767, 0.04386612, 0.9517362 ], dtype=float32),
 array([0.00915053, 0.13984913, 0.85100025], dtype=float32),
 array([0.12409981, 0.4781291 , 0.39777112], dtype=float32),
 array([0.00620839, 0.04718446, 0.9466072 ], dtype=float32),
 array([0.01190744, 0.2443478 , 0.74374485], dtype=float32),
 array([0.07478987, 0.37200132, 0.55320877], dtype=float32),
 array([0.6832924 , 0.29360348, 0.02310408], dtype=float32),
 array([0.9384536 , 0.05643438, 0.00511203], dtype=float32),
 array([0.00327761, 0.02568514, 0.9710371 ], dtype=float32),
 array([0.00707053, 0.19263136, 0.800298  ], dtype=float32),
 array([0.00187848, 0.017666  , 0.9804555 ], dtype=float32),
 array([0.00440548, 0.06054255, 0.9350519 ], dtype=float32),
 array([0.00678404, 0.08844578, 0.9047702 ], dtype=float32),
 array([0.00221842, 0.04